{
 "title": "Beacon node",
 "tags": [
  "Prysm",
  "Beacon node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "offset", "label": "Offset", "query": "63819s" }
  ]
 },
 "panels": [
  { "title": "⏱️Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot/32)",
     "legendFormat": "epoch"
    }
   ]
  },
  {
   "title": "Slot in epoch",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_clock_time_slot%32", "legendFormat": "epoch" }
   ]
  },
  {
   "title": "Validators count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_count", "legendFormat": "{{state}}" },
    { "expr": "sum(validator_count)", "legendFormat": "Total" },
    {
     "expr": "validator_count{state=\"Active\"} / on() group_left sum(validator_count)",
     "legendFormat": "Active rate"
    }
   ]
  },
  {
   "title": "Validators balance (ETH)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validators_total_balance/1_000_000_000",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Distance from tip (time)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(beacon_clock_time_slot-beacon_slot)*12",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_clock_time_slot", "legendFormat": "slot" }
   ]
  },
  {
   "title": "Distance from tip (slots)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_slot",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced new block > 4s [24h]",
   "type": "gauge",
   "description": "The number of blocks synced after the 4 seconds deadline during the last 24 hours, excluding reorged blocks.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "( sum(count_over_time({service_name=\"beacon\", level=\"info\"} |= \"Synced new block\" | logfmt | sinceSlotStartTime > 4s [24h])) - sum(count_over_time({service_name=\"beacon\", level=\"info\"} |= \"Chain reorg occurred\" [24h]))) / 7200"
    }
   ]
  },
  {
   "title": "Backfill completion",
   "type": "gauge",
   "description": "The number of blocks synced after the 4 seconds deadline during the last 24 hours, excluding reorged blocks.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backfill_batches_imported / (backfill_batches_imported + backfill_remaining_batches)"
    }
   ]
  },
  { "title": "⚙️ System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"beacon\"}[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"beacon\"}[2h])",
     "legendFormat": "[2h]"
    }
   ]
  },
  {
   "title": "Memory usage heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"beacon\"}",
     "legendFormat": "[inst]"
    },
    {
     "expr": "avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h])",
     "legendFormat": "[2h]"
    }
   ]
  },
  {
   "title": "CPU steal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " avg(rate(node_cpu_seconds_total{job=\"node\",mode=\"steal\"}[1m]))",
     "legendFormat": "[1m]"
    },
    {
     "expr": " avg(rate(node_cpu_seconds_total{job=\"node\",mode=\"steal\"}[2h]))",
     "legendFormat": "[2h]"
    }
   ]
  },
  {
   "title": "Memory usage stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"beacon\"}",
     "legendFormat": "[inst]"
    },
    {
     "expr": "avg_over_time(go_memstats_stack_sys_bytes{job=\"beacon\"}[2h])",
     "legendFormat": "[2h]"
    }
   ]
  },
  {
   "title": "Pressure waiting [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{job=\"node\"}[5m])",
     "legendFormat": "CPU"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{job=\"node\"}[5m])",
     "legendFormat": "IO"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{job=\"node\"}[5m])",
     "legendFormat": "Memor"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"beacon\"}",
     "legendFormat": "go"
    },
    { "expr": "beacon_goroutine_count", "legendFormat": "{{kind}}" }
   ]
  },
  {
   "title": "Garbage collector duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"beacon\"}[1m])/rate(go_gc_duration_seconds_count{job=\"beacon\"}[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"beacon\"}[20m])/rate(go_gc_duration_seconds_count{job=\"beacon\"}[20m])",
     "legendFormat": "[20m]"
    }
   ]
  },
  { "title": "🌍 Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Peers per direction and type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    { "expr": "p2p_peer_count_direction_type", "legendFormat": "{{direction}}-{{type}}" },
    { "expr": "p2p_max_peers", "legendFormat": "min. target" }
   ]
  },
  {
   "title": "Peers per agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    { "expr": "connected_libp2p_peers", "legendFormat": "{{agent}}" },
    { "expr": "p2p_max_peers", "legendFormat": "min. target" },
    { "expr": "sum(connected_libp2p_peers)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Mesh peers per topic - Static",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "p2p_subscribed_topic_peer_total{topic!~\".*(beacon_attestation|sync_committee_\\\\d|blob_sidecar|data_column_sidecar).*\"}",
     "legendFormat": "{{topic}}"
    },
    { "expr": "p2p_max_peers", "legendFormat": "min. target" }
   ]
  },
  {
   "title": "P2P PubSub validation failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(p2p_pubsub_reject_total{reason=\"validation failed\"}[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Mesh peers per topic - Sync committee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "p2p_subscribed_topic_peer_total{topic=~\".*sync_committee_\\\\d.*\"}",
     "legendFormat": "{{topic}}"
    },
    { "expr": "p2p_minimum_peers_per_subnet", "legendFormat": "min. target" }
   ]
  },
  {
   "title": "Mesh peers per topic - Attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "p2p_subscribed_topic_peer_total{topic=~\".*beacon_attestation.*\"}",
     "legendFormat": "{{topic}}"
    },
    { "expr": "p2p_minimum_peers_per_subnet", "legendFormat": "min. target" }
   ]
  },
  {
   "title": "P2P PubSub validation ignored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "rate(p2p_pubsub_reject_total{reason=\"validation ignored\"}[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total peers per topic - Attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "p2p_topic_peer_count{topic=~\".*beacon_attestation.*\"}",
     "legendFormat": "{{topic}}"
    },
    { "expr": "p2p_minimum_peers_per_subnet", "legendFormat": "min. target" }
   ]
  },
  {
   "title": "Mesh peers per topic - Sidecars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "p2p_subscribed_topic_peer_total{topic=~\".*blob_sidecar.*|.*data_column_sidecar.*\"}",
     "legendFormat": "{{topic}}"
    },
    { "expr": "p2p_minimum_peers_per_subnet", "legendFormat": "min. target" }
   ]
  },
  {
   "title": "Peers ",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "beacon_peer_geo{direction=\"inbound\"}",
     "legendFormat": "{{peer_id}}"
    },
    {
     "expr": "beacon_peer_geo{direction=\"outbound\"}",
     "legendFormat": "{{peer_id}}"
    },
    {
     "expr": "beacon_peer_geo{direction=\"self\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "🧊 Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gossip_block_arrival_milliseconds_sum[16s])/rate(gossip_block_arrival_milliseconds_count[16s])",
     "legendFormat": "gossip arrival time"
    },
    {
     "expr": "rate(gossip_block_verification_milliseconds_sum[16s])/rate(gossip_block_verification_milliseconds_count[16s])",
     "legendFormat": "gossip verification time"
    },
    {
     "expr": "rate(new_payload_v1_latency_milliseconds_sum[16s])/rate(new_payload_v1_latency_milliseconds_count[16s])",
     "legendFormat": "new payload processing time"
    },
    {
     "expr": "rate(da_waited_time_milliseconds_sum[16s])/rate(da_waited_time_milliseconds_count[16s])",
     "legendFormat": "data availability waiting time"
    },
    {
     "expr": "rate(chain_service_processing_milliseconds_sum[16s])/rate(chain_service_processing_milliseconds_count[16s]) - rate(new_payload_v1_latency_milliseconds_sum[16s])/rate(new_payload_v1_latency_milliseconds_count[16s])",
     "legendFormat": "beacon only processing time"
    },
    {
     "expr": "rate(gossip_block_arrival_milliseconds_sum[16s])/rate(gossip_block_arrival_milliseconds_count[16s]) + rate(gossip_block_verification_milliseconds_sum[16s])/rate(gossip_block_verification_milliseconds_count[16s]) +rate(da_waited_time_milliseconds_sum[16s])/rate(da_waited_time_milliseconds_count[16s]) + rate(chain_service_processing_milliseconds_sum[16s])/rate(chain_service_processing_milliseconds_count[16s])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Consolidations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "increase(consolidation_request_count[24s])/2",
     "legendFormat": "current"
    }
   ]
  },
  { "title": "👥 Beacon API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Validator queries rate [5m] - 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(http_request_count{endpoint=~\"validator.*\", code=~\"2..\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Validator queries rate [5m] - 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(http_request_count{endpoint=~\"validator.*\", code=~\"4..\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Validator queries rate [5m] - 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(http_request_count{endpoint=~\"validator.*\", code=~\"5..\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "✍️ Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Attestations in pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "aggregated_attestations_in_pool_total",
     "legendFormat": "aggregated"
    },
    {
     "expr": "unaggregated_attestations_in_pool_total",
     "legendFormat": "unagreggated"
    }
   ]
  },
  {
   "title": "Expired attestations [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "increase(expired_aggregated_atts_total[1h])",
     "legendFormat": "aggregated"
    },
    {
     "expr": "increase(expired_unaggregated_atts_total[1h])",
     "legendFormat": "unagreggated"
    }
   ]
  },
  {
   "title": "Expired block attestations [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "increase(expired_block_atts_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip pending attestations [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase(gossip_pending_attestations_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "💾 Data availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Data column sidecars verification via gossip duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "sum(rate(beacon_data_column_sidecar_gossip_verification_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data column sidecars storage save latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "sum(rate(data_column_storage_save_latency_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data column sidecars verification via gossip duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(beacon_data_column_sidecar_gossip_verification_milliseconds_sum[1m])/rate(beacon_data_column_sidecar_gossip_verification_milliseconds_count[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(beacon_data_column_sidecar_gossip_verification_milliseconds_sum[4h])/rate(beacon_data_column_sidecar_gossip_verification_milliseconds_count[4h])",
     "legendFormat": "[4h]"
    }
   ]
  },
  {
   "title": "Data column sidecars storage save latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(data_column_storage_save_latency_sum[1m])/rate(data_column_storage_save_latency_count[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(data_column_storage_save_latency_sum[4h])/rate(data_column_storage_save_latency_count[4h])",
     "legendFormat": "[4h]"
    }
   ]
  },
  {
   "title": "Blob count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "rate(commitment_count_max_21_sum[1m])/rate(commitment_count_max_21_count[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(commitment_count_max_21_sum[4h])/rate(commitment_count_max_21_count[4h])",
     "legendFormat": "[4h]"
    },
    { "expr": "max_blobs_per_block", "legendFormat": "max" }
   ]
  },
  {
   "title": "Data column sidecars file save sync latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(data_column_file_sync_latency_sum[1m])/rate(data_column_file_sync_latency_count[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(data_column_file_sync_latency_sum[4h])/rate(data_column_file_sync_latency_count[4h])",
     "legendFormat": "[4h]"
    }
   ]
  },
  {
   "title": "Data column sidecars KZG proof verification duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "sum(rate(beacon_kzg_verification_data_column_batch_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data column sidecars batch save count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "targets": [
    {
     "expr": "rate(data_column_batch_store_count_sum[1m])/rate(data_column_batch_store_count_count[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(data_column_batch_store_count_sum[4h])/rate(data_column_batch_store_count_count[4h])",
     "legendFormat": "[4h]"
    }
   ]
  },
  {
   "title": "Cells and proofs from structured computation duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "sum(rate(cells_and_proofs_from_structured_computation_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "getBlobsV2 duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "sum(rate(get_blobs_v2_latency_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data column sidecars arrival time via gossip since slot start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gossip_data_column_sidecar_arrival_milliseconds_sum[1m])/rate(gossip_data_column_sidecar_arrival_milliseconds_count[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(gossip_data_column_sidecar_arrival_milliseconds_sum[4h])/rate(gossip_data_column_sidecar_arrival_milliseconds_count[4h])",
     "legendFormat": "[4h]"
    }
   ]
  },
  { "title": "🚶State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 } },
  {
   "title": "Beacon state count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "targets": [
    { "expr": "beacon_state_count", "legendFormat": "[inst]" },
    {
     "expr": "avg_over_time(beacon_state_count[1h])",
     "legendFormat": "[1h]"
    }
   ]
  },
  {
   "title": "Data column sidecars construction from execution layer success rate (getBlobsV2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(data_columns_recovered_from_el_total[5m])/rate(data_columns_recovered_from_el_attempts[5m])",
     "legendFormat": "[5m]"
    },
    {
     "expr": "rate(data_columns_recovered_from_el_total[4h])/rate(data_columns_recovered_from_el_attempts[4h])",
     "legendFormat": "[4h]"
    }
   ]
  },
  {
   "title": "Next slot cache hit rate [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(next_slot_cache_hit[1h])/(increase(next_slot_cache_miss[1h])+increase(next_slot_cache_hit[1h]))",
     "legendFormat": "hit"
    }
   ]
  },
  {
   "title": "Head state defragmentation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(head_state_defragmentation_milliseconds_sum[1m])/rate(head_state_defragmentation_milliseconds_count[1m])",
     "legendFormat": "[1m]"
    },
    {
     "expr": "rate(head_state_defragmentation_milliseconds_sum[1h])/rate(head_state_defragmentation_milliseconds_count[1h])",
     "legendFormat": "[1h]"
    }
   ]
  },
  {
   "title": "Multi value individual element references",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "targets": [
    {
     "expr": "multi_value_individual_element_references_count",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Multi value appended elements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "targets": [
    {
     "expr": "multi_value_appended_elements_count",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Multi value appended element references",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "multi_value_appended_element_references_count",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Multi value objects count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
   "targets": [
    { "expr": "multi_value_object_count", "legendFormat": "{{field}}" }
   ]
  },
  {
   "title": "Checkpoint state cache [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "targets": [
    {
     "expr": "increase(check_point_state_cache_hit[1h])",
     "legendFormat": "hit"
    },
    {
     "expr": "increase(check_point_state_cache_miss[1h])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Multi value individual elements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "targets": [
    {
     "expr": "multi_value_individual_elements_count",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Hot state cache hit rate [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(hot_state_cache_hit[1h])/(increase(hot_state_cache_miss[1h])+increase(hot_state_cache_hit[1h]))",
     "legendFormat": "hit"
    }
   ]
  },
  {
   "title": "State caches size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
   "targets": [
    { "expr": "check_point_state_cache_size", "legendFormat": "checkpoint" },
    {
     "expr": "epoch_boundary_state_cache_size",
     "legendFormat": "epoch boundary"
    }
   ]
  },
  {
   "title": "Average overrides leaf count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
   "targets": [
    {
     "expr": "field_trie_leaf_overrides / on(field) field_trie_count{mode=\"overlay\"}",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Field trie owned count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 244 },
   "targets": [
    {
     "expr": "field_trie_count{mode=\"owned\"}",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Field trie overlay count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 252 },
   "targets": [
    {
     "expr": "field_trie_count{mode=\"overlay\"}",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Field trie nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 252 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "field_trie_entries{component=\"nodes\"} * 32",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "sum(field_trie_entries{component=\"nodes\"}) * 32",
     "legendFormat": "total (nodes)"
    },
    { "expr": "sum(field_trie_entries) * 32", "legendFormat": "total (nodes + overrides)" }
   ]
  },
  {
   "title": "Field trie promotions [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
   "targets": [
    {
     "expr": "increase(field_trie_promotion_total[10m])",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Field trie overrides",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "field_trie_entries{component=\"overrides\"} * 32",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "sum(field_trie_entries{component=\"overrides\"})*32",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Save state duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "increase(save_state_to_cold_milliseconds_sum[1h])/(increase(save_state_to_cold_milliseconds_count[1h]))",
     "legendFormat": "hit"
    }
   ]
  },
  { "title": "🌳 Fork choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 276 } },
  {
   "title": "Finalized epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 277 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "finalized_epoch", "text": "epoch", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/layout?ts=${__to}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Justified epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 277 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "justified_epoch", "text": "epoch", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/layout?ts=${__to}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 277 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "head_slot", "text": "head_slot", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/layout?ts=${__to}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Fork choice tree",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 281 },
   "targets": [
    {
     "columns": [
      { "selector": "slot", "text": "slot", "type": "number" },
      { "selector": "y", "text": "y", "type": "number" },
      { "selector": "block_root", "text": "block_root", "type": "string" },
      { "selector": "parent_root", "text": "parent_root", "type": "string" },
      { "selector": "weight", "text": "weight", "type": "string" },
      { "selector": "validity", "text": "validity", "type": "string" },
      { "selector": "kind", "text": "kind", "type": "string" },
      { "selector": "is_head", "text": "is_head", "type": "boolean" },
      { "selector": "is_optimistic", "text": "is_optimistic", "type": "boolean" }
     ],
     "parser": "backend",
     "root_selector": "nodes",
     "source": "url",
     "type": "json",
     "url": "/layout?ts=${__to}",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "from_slot", "text": "from_slot", "type": "number" },
      { "selector": "from_y", "text": "from_y", "type": "number" },
      { "selector": "to_slot", "text": "to_slot", "type": "number" },
      { "selector": "to_y", "text": "to_y", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "edges",
     "source": "url",
     "type": "json",
     "url": "/layout?ts=${__to}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Fork choice nodes",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 299 },
   "targets": [
    {
     "columns": [
      { "selector": "slot", "text": "slot", "type": "number" },
      { "selector": "kind", "text": "kind", "type": "string" },
      { "selector": "is_head", "text": "head", "type": "boolean" },
      { "selector": "is_optimistic", "text": "optimistic", "type": "boolean" },
      { "selector": "block_root", "text": "block_root", "type": "string" },
      { "selector": "parent_root", "text": "parent_root", "type": "string" },
      { "selector": "weight", "text": "weight", "type": "string" },
      { "selector": "validity", "text": "validity", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "nodes",
     "source": "url",
     "type": "json",
     "url": "/layout?ts=${__to}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "⏯️ Replay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 311 } },
  {
   "title": "Memory usage heap [inst]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 312 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"beacon\"}",
     "legendFormat": "current"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"beacon\"} offset ${offset}",
     "legendFormat": "ref"
    }
   ]
  },
  {
   "title": "Memory usage heap [2h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 312 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h])",
     "legendFormat": "current"
    },
    {
     "expr": "avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h] offset ${offset})",
     "legendFormat": "ref"
    }
   ]
  },
  {
   "title": "Memory usage heap diff [2h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 320 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h] offset ${offset}) - avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h])",
     "legendFormat": "absolute"
    },
    {
     "expr": "(avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h] offset ${offset}) - avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h]))/avg_over_time(go_memstats_alloc_bytes{job=\"beacon\"}[2h] offset ${offset})",
     "legendFormat": "relative"
    }
   ]
  },
  {
   "title": "Chain service processing time [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 320 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(chain_service_processing_milliseconds_sum[1m])/rate(chain_service_processing_milliseconds_count[1m])",
     "legendFormat": "current"
    },
    {
     "expr": "rate(chain_service_processing_milliseconds_sum[1m] offset ${offset}) / rate(chain_service_processing_milliseconds_count[1m] offset ${offset})",
     "legendFormat": "ref"
    }
   ]
  },
  { "title": "🚰 Backfill", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 328 } },
  {
   "title": "Earliest slot assigned to a worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    { "expr": "backfill_earliest_wip_slot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of batches that are ready to be imported once they can be connected to the existing chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 329 },
   "targets": [
    {
     "expr": "backfill_importable_batches_waiting",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches imports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "backfill_remaining_batches", "legendFormat": "Remaining" },
    { "expr": "backfill_batches_imported", "legendFormat": "Imported" }
   ]
  },
  {
   "title": "Downloaded blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 337 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "backfill_blocks_download_count", "legendFormat": "Blocks" },
    {
     "expr": "backfill_blocks_bytes_downloaded",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Downloaded data column sidecars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 345 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "backfill_data_column_sidecar_downloaded",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}