apiVersion: 1
datasources:
  - id: 1
    uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/plugins/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus:9090
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
      pdcInjected: false
      prometheusType: Prometheus
      prometheusVersion: 2.50.1
      timeInterval: 12s
    readOnly: false
  - id: 2
    uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    typeLogoUrl: public/plugins/loki/img/loki_icon.svg
    access: proxy
    url: http://loki:3100
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      pdcInjected: false
    readOnly: false
  - id: 3
    uid: pyroscope
    orgId: 1
    name: Pyroscope
    type: grafana-pyroscope-datasource
    typeName: Grafana Pyroscope
    typeLogoUrl: public/plugins/grafana-pyroscope-datasource/img/grafana_pyroscope_icon.svg
    access: proxy
    url: http://pyroscope:4040
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      pdcInjected: false
    readOnly: false
  - id: 4
    uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    typeLogoUrl: public/app/plugins/datasource/tempo/img/tempo_logo.svg
    access: proxy
    url: http://tempo:3200
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      pdcInjected: false
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
      tracesToMetrics:
        datasourceUid: prometheus
    readOnly: false
